### ISSUE TITLE
[Fix] 로그 정리 및 UI 다듬기

### ISSUE THREAD

**Issue by yh-project** [YU-RentCar/yurentcar-fe-web-v2#137]
## 📔 Description
- 개발이 완료된 경우는 로그를 정리
- 크기가 너무 크거나 작거나 등의 UI 들 다듬기
- UI 조정에 따른 SideMenu 추가

## 🐈 Todo

- [x] 마이페이지 로그 정리
- [x] 마이페이지 UI 다듬기
- [x] 마이페이지 SideMenu 추가
