### ISSUE TITLE
[Feat] 사용자 홈 화면 지역 선택 기능 추가

### ISSUE THREAD

**Issue by seolbotdae** [YU-RentCar/yurentcar-fe-web-v2#16]
## 📔 Description

사용자 홈 화면에서 지역을 선택하는 기능을 구현하기 위해 이슈 개설

![스크린샷 2023-09-22 오후 9 10 36](https://github.com/YU-RentCar/yurentcar-fe-web-v2/assets/54520200/68c56bfd-f481-402f-b999-def48cdefbf1)

- 무슨무슨 점 이런 식으로 되어있는 부분이 지역 선택이다.

## 🐈 Todo

- [x] 지역 선택 버튼 클릭 시 팝업 생성
- [x] 팝업에서 사용자가 사용할 수 있는 지도 추가
- [x] 성공적으로 사용자가 선택한 지점으로 변경
