### ISSUE TITLE
[Fix] 마이페이지 관련 버그 및 UI 수정

### ISSUE THREAD

**Issue by yh-project** [YU-RentCar/yurentcar-fe-web-v2#160]
## 📔 Description
마이페이지 관련 버그 및 UI 수정

## 🐈 Todo

- [x] UI 고정
- [x] 포인트 사용 내역 여백 추가
- [x] 예약 내역 y축 gap 추가
- [x] 최근 본 차량 조회 hover 제거
