### ISSUE TITLE
[Fix] 공지사항 관련 UI 및 버그 수정

### ISSUE THREAD

**Issue by yh-project** [YU-RentCar/yurentcar-fe-web-v2#162]
## 📔 Description
공지사항 관련 UI 및 버그 수정

## 🐈 Todo

- [x] api 에 필요한 정보 이용 방식 변경
- [x] 남은날짜 보여주는 방식 변경
- [x] 공지사항 내용 Viewer 적용
