### ISSUE TITLE
[Feat] 차량 검색 페이지 UI 제작

### ISSUE THREAD

**Issue by seolbotdae** [YU-RentCar/yurentcar-fe-web-v2#48]
## 📔 Description

차량 검색 페이지 UI 제작

## 🐈 Todo

- [x] 선호차량 검색을 위한 검색 기능
- [x] 하단의 작은 공지사항 기능
- [x] 차량 리스트 UI
