### ISSUE TITLE
[Feat] 마이페이지 렌트 대기, 기본 정보, 선호 차량 옵션 api 로직 구현

### ISSUE THREAD

**Issue by yh-project** [YU-RentCar/yurentcar-fe-web-v2#85]
## 📔 Description
마이페이지에서 필요한 api 로직들 구현

## 🐈 Todo

- [x] 렌트 대기 정보 api
- [x] 사용자 기본 정보 api
- [x] 사용자 선호 차량 옵션 api
