### ISSUE TITLE
[Feat] 예약 페이지 차량 기본&상세 정보, 수리&사고 내역, 지도 조회 api 구현

### ISSUE THREAD

**Issue by yh-project** [YU-RentCar/yurentcar-fe-web-v2#96]
## 📔 Description
예약 페이지의 차량 기본&상세 정보, 수리&사고 내역, 지점 지도 조회 구현

## 🐈 Todo

- [x] 차량 기본 정보 조회 api 구현
- [x] 차량 상세 정보 조회 api 구현
- [x] 차량 수리 내역 조회 api 구현
- [x] 차량 사고 내역 조회 api 구현
- [x] 차량이 속하는 지점 지도에서 조회 api 구현
